
obj-y += hal/halAESDMA.o
ccflags-y += -I$(srctree)/$(src)/hal
obj-y += drvAESDMA.o
obj-$(CONFIG_CMD_SIGAUTH) += cmd_sigauth.o
obj-$(CONFIG_CMD_VERIFYAESDMA) += cmd_verifyaes.o


ccflags-y += -I$(srctree)/$(src)

