/*
* reg_hdmitx_packet.h- Sigmastar
*
* Copyright (c) [2019~2020] SigmaStar Technology.
*
*
* This software is licensed under the terms of the GNU General Public
* License version 2, as published by the Free Software Foundation, and
* may be copied, distributed, and modified under those terms.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License version 2 for more details.
*
*/
#ifndef __REG_HDMITX_PACKET__
#define __REG_HDMITX_PACKET__

#define REG_AVI_BASE    (HDMI_TX_REG_AVI_S0)
#define REG_ADO_BASE    (HDMI_TX_REG_ADO_S0)
#define REG_ASP_CS_BASE (HDMI_TX_REG_ASP_CH_STATUS)
#define REG_SPD_HD_BASE (HDMI_TX_REG_PKT0_HD)
#define REG_SPD_BASE    (HDMI_TX_REG_PKT0_S0)
#define REG_VS_HD_BASE  (HDMI_TX_REG_PKT1_HD)
#define REG_VS_BASE     (HDMI_TX_REG_PKT1_S0)
// h0000, bit: 7
/* checksum*/
#define offset_of_avi_checksum (0x0)
#define mask_of_avi_checksum   (0xff)
#define shift_of_avi_checksum  (0)
#define AVI_CHECKSUM           (REG_AVI_BASE + offset_of_avi_checksum)
#define REG_AVI_00_L           (AVI_CHECKSUM)
// h0000, bit: 9
/* overscan or underscan*/
#define offset_of_avi_scan_info (0x0)
#define mask_of_avi_scan_info   (0x300)
#define shift_of_avi_scan_info  (8)
#define AVI_SCAN_INFO           (REG_AVI_BASE + offset_of_avi_scan_info)
// h0000, bit: 11
/* bar info data vaild.*/
#define offset_of_avi_bar_info (0x0)
#define mask_of_avi_bar_info   (0xc00)
#define shift_of_avi_bar_info  (10)
#define AVI_BAR_INFO           (REG_AVI_BASE + offset_of_avi_bar_info)
// h0000, bit: 12
/* active info present*/
#define offset_of_avi_active_info (0x0)
#define mask_of_avi_active_info   (0x1000)
#define shift_of_avi_active_info  (12)
#define AVI_ACTIVE_INFO           (REG_AVI_BASE + offset_of_avi_active_info)
// h0000, bit: 14
/* RGB or YCbCr*/
#define offset_of_avi_color_indicator (0x0)
#define mask_of_avi_color_indicator   (0x6000)
#define shift_of_avi_color_indicator  (13)
#define AVI_COLOR_INDICATOR           (REG_AVI_BASE + offset_of_avi_color_indicator)
// h0001, bit: 3
/* active_format_aspect_ratio*/
#define offset_of_avi_active_format_aspect_ratio (0x2)
#define mask_of_avi_active_format_aspect_ratio   (0xf)
#define shift_of_avi_active_format_aspect_ratio  (0)
#define AVI_ACTIVE_FORMAT_ASPECT_RATIO           (REG_AVI_BASE + offset_of_avi_active_format_aspect_ratio)
#define REG_AVI_01_L                             (AVI_ACTIVE_FORMAT_ASPECT_RATIO)
// h0001, bit: 5
/* picture_aspect_ratio*/
#define offset_of_avi_picture_aspect_ratio (0x2)
#define mask_of_avi_picture_aspect_ratio   (0x30)
#define shift_of_avi_picture_aspect_ratio  (4)
#define AVI_PICTURE_ASPECT_RATIO           (REG_AVI_BASE + offset_of_avi_picture_aspect_ratio)
// h0001, bit: 7
/* colorimetry*/
#define offset_of_avi_colorimetry (0x2)
#define mask_of_avi_colorimetry   (0xc0)
#define shift_of_avi_colorimetry  (6)
#define AVI_COLORIMETRY           (REG_AVI_BASE + offset_of_avi_colorimetry)
// h0001, bit: 9
/* Non_uniform_picture_scaling*/
#define offset_of_avi_Non_uniform_picture_scaling (0x2)
#define mask_of_avi_Non_uniform_picture_scaling   (0x300)
#define shift_of_avi_Non_uniform_picture_scaling  (8)
#define AVI_NON_UNIFORM_PICTURE_SCALING           (REG_AVI_BASE + offset_of_avi_Non_uniform_picture_scaling)
// h0001, bit: 11
/* quantization_range*/
#define offset_of_avi_quantization_range (0x2)
#define mask_of_avi_quantization_range   (0xc00)
#define shift_of_avi_quantization_range  (10)
#define AVI_QUANTIZATION_RANGE           (REG_AVI_BASE + offset_of_avi_quantization_range)
// h0001, bit: 14
/* ext_colorimetry*/
#define offset_of_avi_ext_colorimetry (0x2)
#define mask_of_avi_ext_colorimetry   (0x7000)
#define shift_of_avi_ext_colorimetry  (12)
#define AVI_EXT_COLORIMETRY           (REG_AVI_BASE + offset_of_avi_ext_colorimetry)
// h0001, bit: 15
/* it content*/
#define offset_of_avi_ITC (0x2)
#define mask_of_avi_ITC   (0x8000)
#define shift_of_avi_ITC  (15)
#define AVI_ITC           (REG_AVI_BASE + offset_of_avi_ITC)
// h0002, bit: 6
/* vedio format id code.*/
#define offset_of_avi_VIC (0x4)
#define mask_of_avi_VIC   (0x7f)
#define shift_of_avi_VIC  (0)
#define AVI_VIC           (REG_AVI_BASE + offset_of_avi_VIC)
#define REG_AVI_02_L      (AVI_VIC)
// h0002, bit: 11
/* pixel_repetition*/
#define offset_of_avi_pixel_repetition (0x4)
#define mask_of_avi_pixel_repetition   (0xf00)
#define shift_of_avi_pixel_repetition  (8)
#define AVI_PIXEL_REPETITION           (REG_AVI_BASE + offset_of_avi_pixel_repetition)
// h0002, bit: 13
/* content_type*/
#define offset_of_avi_content_type (0x4)
#define mask_of_avi_content_type   (0x3000)
#define shift_of_avi_content_type  (12)
#define AVI_CONTENT_TYPE           (REG_AVI_BASE + offset_of_avi_content_type)
// h0002, bit: 15
/* YCC Quantization*/
#define offset_of_avi_YCC (0x4)
#define mask_of_avi_YCC   (0xc000)
#define shift_of_avi_YCC  (14)
#define AVI_YCC           (REG_AVI_BASE + offset_of_avi_YCC)
// h0003, bit: 15
/* char*/
#define offset_of_avi_line_num_end (0x6)
#define mask_of_avi_line_num_end   (0xffff)
#define shift_of_avi_line_num_end  (0)
#define AVI_LINE_NUM_END           (REG_AVI_BASE + offset_of_avi_line_num_end)
#define REG_AVI_03_L               (AVI_LINE_NUM_END)
// h0004, bit: 15
/* char*/
#define offset_of_avi_line_num_start (0x8)
#define mask_of_avi_line_num_start   (0xffff)
#define shift_of_avi_line_num_start  (0)
#define AVI_LINE_NUM_START           (REG_AVI_BASE + offset_of_avi_line_num_start)
#define REG_AVI_04_L                 (AVI_LINE_NUM_START)
// h0005, bit: 15
/* char*/
#define offset_of_avi_pixel_num_End (0xa)
#define mask_of_avi_pixel_num_End   (0xffff)
#define shift_of_avi_pixel_num_End  (0)
#define AVI_PIXEL_NUM_END           (REG_AVI_BASE + offset_of_avi_pixel_num_End)
#define REG_AVI_05_L                (AVI_PIXEL_NUM_END)
// h0006, bit: 15
/* char*/
#define offset_of_avi_pixel_num_start (0xc)
#define mask_of_avi_pixel_num_start   (0xffff)
#define shift_of_avi_pixel_num_start  (0)
#define AVI_PIXEL_NUM_START           (REG_AVI_BASE + offset_of_avi_pixel_num_start)
#define REG_AVI_06_L                  (AVI_PIXEL_NUM_START)
#define REG_AVI_07_L                  (REG_AVI_BASE + 0xe)
#define REG_AVI_08_L                  (REG_AVI_BASE + 0x10)
#define REG_AVI_09_L                  (REG_AVI_BASE + 0x12)
#define REG_AVI_0A_L                  (REG_AVI_BASE + 0x14)
#define REG_AVI_0B_L                  (REG_AVI_BASE + 0x16)
#define REG_AVI_0C_L                  (REG_AVI_BASE + 0x18)
#define REG_AVI_0D_L                  (REG_AVI_BASE + 0x1a)
#define REG_AVI_0E_L                  (REG_AVI_BASE + 0x1c)
#define REG_AVI_0F_L                  (REG_AVI_BASE + 0x1e)
#define REG_AVI_10_L                  (REG_AVI_BASE + 0x20)
#define REG_AVI_11_L                  (REG_AVI_BASE + 0x22)
#define REG_AVI_12_L                  (REG_AVI_BASE + 0x24)
#define REG_AVI_13_L                  (REG_AVI_BASE + 0x26)
#define REG_AVI_14_L                  (REG_AVI_BASE + 0x28)
#define REG_AVI_15_L                  (REG_AVI_BASE + 0x2a)
#define REG_AVI_16_L                  (REG_AVI_BASE + 0x2c)
#define REG_AVI_17_L                  (REG_AVI_BASE + 0x2e)
#define REG_AVI_18_L                  (REG_AVI_BASE + 0x30)
#define REG_AVI_19_L                  (REG_AVI_BASE + 0x32)
#define REG_AVI_1A_L                  (REG_AVI_BASE + 0x34)
#define REG_AVI_1B_L                  (REG_AVI_BASE + 0x36)
#define REG_AVI_1C_L                  (REG_AVI_BASE + 0x38)
#define REG_AVI_1D_L                  (REG_AVI_BASE + 0x3a)
#define REG_AVI_1E_L                  (REG_AVI_BASE + 0x3c)
#define REG_AVI_1F_L                  (REG_AVI_BASE + 0x3e)
#define REG_AVI_20_L                  (REG_AVI_BASE + 0x40)
#define REG_AVI_21_L                  (REG_AVI_BASE + 0x42)
#define REG_AVI_22_L                  (REG_AVI_BASE + 0x44)
#define REG_AVI_23_L                  (REG_AVI_BASE + 0x46)
#define REG_AVI_24_L                  (REG_AVI_BASE + 0x48)
#define REG_AVI_25_L                  (REG_AVI_BASE + 0x4a)
#define REG_AVI_26_L                  (REG_AVI_BASE + 0x4c)
#define REG_AVI_27_L                  (REG_AVI_BASE + 0x4e)
#define REG_AVI_28_L                  (REG_AVI_BASE + 0x50)
#define REG_AVI_29_L                  (REG_AVI_BASE + 0x52)
#define REG_AVI_2A_L                  (REG_AVI_BASE + 0x54)
#define REG_AVI_2B_L                  (REG_AVI_BASE + 0x56)
#define REG_AVI_2C_L                  (REG_AVI_BASE + 0x58)
#define REG_AVI_2D_L                  (REG_AVI_BASE + 0x5a)
#define REG_AVI_2E_L                  (REG_AVI_BASE + 0x5c)
#define REG_AVI_2F_L                  (REG_AVI_BASE + 0x5e)
#define REG_AVI_30_L                  (REG_AVI_BASE + 0x60)
#define REG_AVI_31_L                  (REG_AVI_BASE + 0x62)
#define REG_AVI_32_L                  (REG_AVI_BASE + 0x64)
#define REG_AVI_33_L                  (REG_AVI_BASE + 0x66)
#define REG_AVI_34_L                  (REG_AVI_BASE + 0x68)
#define REG_AVI_35_L                  (REG_AVI_BASE + 0x6a)
#define REG_AVI_36_L                  (REG_AVI_BASE + 0x6c)
#define REG_AVI_37_L                  (REG_AVI_BASE + 0x6e)
#define REG_AVI_38_L                  (REG_AVI_BASE + 0x70)
#define REG_AVI_39_L                  (REG_AVI_BASE + 0x72)
#define REG_AVI_3A_L                  (REG_AVI_BASE + 0x74)
#define REG_AVI_3B_L                  (REG_AVI_BASE + 0x76)
#define REG_AVI_3C_L                  (REG_AVI_BASE + 0x78)
#define REG_AVI_3D_L                  (REG_AVI_BASE + 0x7a)
#define REG_AVI_3E_L                  (REG_AVI_BASE + 0x7c)
#define REG_AVI_3F_L                  (REG_AVI_BASE + 0x7e)
#define REG_AVI_40_L                  (REG_AVI_BASE + 0x80)
#define REG_AVI_41_L                  (REG_AVI_BASE + 0x82)
#define REG_AVI_42_L                  (REG_AVI_BASE + 0x84)
#define REG_AVI_43_L                  (REG_AVI_BASE + 0x86)
#define REG_AVI_44_L                  (REG_AVI_BASE + 0x88)
#define REG_AVI_45_L                  (REG_AVI_BASE + 0x8a)
#define REG_AVI_46_L                  (REG_AVI_BASE + 0x8c)
#define REG_AVI_47_L                  (REG_AVI_BASE + 0x8e)
#define REG_AVI_48_L                  (REG_AVI_BASE + 0x90)
#define REG_AVI_49_L                  (REG_AVI_BASE + 0x92)
#define REG_AVI_4A_L                  (REG_AVI_BASE + 0x94)
#define REG_AVI_4B_L                  (REG_AVI_BASE + 0x96)
#define REG_AVI_4C_L                  (REG_AVI_BASE + 0x98)
#define REG_AVI_4D_L                  (REG_AVI_BASE + 0x9a)
#define REG_AVI_4E_L                  (REG_AVI_BASE + 0x9c)
#define REG_AVI_4F_L                  (REG_AVI_BASE + 0x9e)
#define REG_AVI_50_L                  (REG_AVI_BASE + 0xa0)
#define REG_AVI_51_L                  (REG_AVI_BASE + 0xa2)
#define REG_AVI_52_L                  (REG_AVI_BASE + 0xa4)
#define REG_AVI_53_L                  (REG_AVI_BASE + 0xa6)
#define REG_AVI_54_L                  (REG_AVI_BASE + 0xa8)
#define REG_AVI_55_L                  (REG_AVI_BASE + 0xaa)
#define REG_AVI_56_L                  (REG_AVI_BASE + 0xac)
#define REG_AVI_57_L                  (REG_AVI_BASE + 0xae)
#define REG_AVI_58_L                  (REG_AVI_BASE + 0xb0)
#define REG_AVI_59_L                  (REG_AVI_BASE + 0xb2)
#define REG_AVI_5A_L                  (REG_AVI_BASE + 0xb4)
#define REG_AVI_5B_L                  (REG_AVI_BASE + 0xb6)
#define REG_AVI_5C_L                  (REG_AVI_BASE + 0xb8)
#define REG_AVI_5D_L                  (REG_AVI_BASE + 0xba)
#define REG_AVI_5E_L                  (REG_AVI_BASE + 0xbc)
#define REG_AVI_5F_L                  (REG_AVI_BASE + 0xbe)
#define REG_AVI_60_L                  (REG_AVI_BASE + 0xc0)
#define REG_AVI_61_L                  (REG_AVI_BASE + 0xc2)
#define REG_AVI_62_L                  (REG_AVI_BASE + 0xc4)
#define REG_AVI_63_L                  (REG_AVI_BASE + 0xc6)
#define REG_AVI_64_L                  (REG_AVI_BASE + 0xc8)
#define REG_AVI_65_L                  (REG_AVI_BASE + 0xca)
#define REG_AVI_66_L                  (REG_AVI_BASE + 0xcc)
#define REG_AVI_67_L                  (REG_AVI_BASE + 0xce)
#define REG_AVI_68_L                  (REG_AVI_BASE + 0xd0)
#define REG_AVI_69_L                  (REG_AVI_BASE + 0xd2)
#define REG_AVI_6A_L                  (REG_AVI_BASE + 0xd4)
#define REG_AVI_6B_L                  (REG_AVI_BASE + 0xd6)
#define REG_AVI_6C_L                  (REG_AVI_BASE + 0xd8)
#define REG_AVI_6D_L                  (REG_AVI_BASE + 0xda)
#define REG_AVI_6E_L                  (REG_AVI_BASE + 0xdc)
#define REG_AVI_6F_L                  (REG_AVI_BASE + 0xde)
#define REG_AVI_70_L                  (REG_AVI_BASE + 0xe0)
#define REG_AVI_71_L                  (REG_AVI_BASE + 0xe2)
#define REG_AVI_72_L                  (REG_AVI_BASE + 0xe4)
#define REG_AVI_73_L                  (REG_AVI_BASE + 0xe6)
#define REG_AVI_74_L                  (REG_AVI_BASE + 0xe8)
#define REG_AVI_75_L                  (REG_AVI_BASE + 0xea)
#define REG_AVI_76_L                  (REG_AVI_BASE + 0xec)
#define REG_AVI_77_L                  (REG_AVI_BASE + 0xee)
#define REG_AVI_78_L                  (REG_AVI_BASE + 0xf0)
#define REG_AVI_79_L                  (REG_AVI_BASE + 0xf2)
#define REG_AVI_7A_L                  (REG_AVI_BASE + 0xf4)
#define REG_AVI_7B_L                  (REG_AVI_BASE + 0xf6)
#define REG_AVI_7C_L                  (REG_AVI_BASE + 0xf8)
#define REG_AVI_7D_L                  (REG_AVI_BASE + 0xfa)
#define REG_AVI_7E_L                  (REG_AVI_BASE + 0xfc)
#define REG_AVI_7F_L                  (REG_AVI_BASE + 0xfe)
// h0000, bit: 7
/* checksum*/
#define offset_of_ado_checksum (0x0)
#define mask_of_ado_checksum   (0xff)
#define shift_of_ado_checksum  (0)
#define ADO_CHECKSUM           (REG_ADO_BASE + offset_of_ado_checksum)
#define REG_ADO_00_L           (ADO_CHECKSUM)
// h0000, bit: 10
/* char*/
#define offset_of_ado_channel_count (0x0)
#define mask_of_ado_channel_count   (0x700)
#define shift_of_ado_channel_count  (8)
#define ADO_CHANNEL_COUNT           (REG_ADO_BASE + offset_of_ado_channel_count)
// h0001, bit: 7
/* char*/
#define offset_of_ado_pk_2 (0x2)
#define mask_of_ado_pk_2   (0xff)
#define shift_of_ado_pk_2  (0)
#define ADO_PK_2           (REG_ADO_BASE + offset_of_ado_pk_2)
#define REG_ADO_01_L       (ADO_PK_2)
// h0001, bit: 15
/* char*/
#define offset_of_ado_pk_3 (0x2)
#define mask_of_ado_pk_3   (0xff00)
#define shift_of_ado_pk_3  (8)
#define ADO_PK_3           (REG_ADO_BASE + offset_of_ado_pk_3)
// h0002, bit: 7
/* char*/
#define offset_of_ado_channel_allocation (0x4)
#define mask_of_ado_channel_allocation   (0xff)
#define shift_of_ado_channel_allocation  (0)
#define ADO_CHANNEL_ALLOCATION           (REG_ADO_BASE + offset_of_ado_channel_allocation)
#define REG_ADO_02_L                     (ADO_CHANNEL_ALLOCATION)
// h0002, bit: 8
/* char*/
#define offset_of_ado_LFEP (0x4)
#define mask_of_ado_LFEP   (0x100)
#define shift_of_ado_LFEP  (8)
#define ADO_LFEP           (REG_ADO_BASE + offset_of_ado_LFEP)
#define REG_ADO_03_L       (REG_ADO_BASE + 0x6)
#define REG_ADO_04_L       (REG_ADO_BASE + 0x8)
#define REG_ADO_05_L       (REG_ADO_BASE + 0xa)
#define REG_ADO_06_L       (REG_ADO_BASE + 0xc)
#define REG_ADO_07_L       (REG_ADO_BASE + 0xe)
#define REG_ADO_08_L       (REG_ADO_BASE + 0x10)
#define REG_ADO_09_L       (REG_ADO_BASE + 0x12)
#define REG_ADO_0A_L       (REG_ADO_BASE + 0x14)
#define REG_ADO_0B_L       (REG_ADO_BASE + 0x16)
#define REG_ADO_0C_L       (REG_ADO_BASE + 0x18)
#define REG_ADO_0D_L       (REG_ADO_BASE + 0x1a)
#define REG_ADO_0E_L       (REG_ADO_BASE + 0x1c)
#define REG_ADO_0F_L       (REG_ADO_BASE + 0x1e)
#define REG_ADO_10_L       (REG_ADO_BASE + 0x20)
#define REG_ADO_11_L       (REG_ADO_BASE + 0x22)
#define REG_ADO_12_L       (REG_ADO_BASE + 0x24)
#define REG_ADO_13_L       (REG_ADO_BASE + 0x26)
#define REG_ADO_14_L       (REG_ADO_BASE + 0x28)
#define REG_ADO_15_L       (REG_ADO_BASE + 0x2a)
#define REG_ADO_16_L       (REG_ADO_BASE + 0x2c)
#define REG_ADO_17_L       (REG_ADO_BASE + 0x2e)
#define REG_ADO_18_L       (REG_ADO_BASE + 0x30)
#define REG_ADO_19_L       (REG_ADO_BASE + 0x32)
#define REG_ADO_1A_L       (REG_ADO_BASE + 0x34)
#define REG_ADO_1B_L       (REG_ADO_BASE + 0x36)
#define REG_ADO_1C_L       (REG_ADO_BASE + 0x38)
#define REG_ADO_1D_L       (REG_ADO_BASE + 0x3a)
#define REG_ADO_1E_L       (REG_ADO_BASE + 0x3c)
#define REG_ADO_1F_L       (REG_ADO_BASE + 0x3e)
#define REG_ADO_20_L       (REG_ADO_BASE + 0x40)
#define REG_ADO_21_L       (REG_ADO_BASE + 0x42)
#define REG_ADO_22_L       (REG_ADO_BASE + 0x44)
#define REG_ADO_23_L       (REG_ADO_BASE + 0x46)
#define REG_ADO_24_L       (REG_ADO_BASE + 0x48)
#define REG_ADO_25_L       (REG_ADO_BASE + 0x4a)
#define REG_ADO_26_L       (REG_ADO_BASE + 0x4c)
#define REG_ADO_27_L       (REG_ADO_BASE + 0x4e)
#define REG_ADO_28_L       (REG_ADO_BASE + 0x50)
#define REG_ADO_29_L       (REG_ADO_BASE + 0x52)
#define REG_ADO_2A_L       (REG_ADO_BASE + 0x54)
#define REG_ADO_2B_L       (REG_ADO_BASE + 0x56)
#define REG_ADO_2C_L       (REG_ADO_BASE + 0x58)
#define REG_ADO_2D_L       (REG_ADO_BASE + 0x5a)
#define REG_ADO_2E_L       (REG_ADO_BASE + 0x5c)
#define REG_ADO_2F_L       (REG_ADO_BASE + 0x5e)
#define REG_ADO_30_L       (REG_ADO_BASE + 0x60)
#define REG_ADO_31_L       (REG_ADO_BASE + 0x62)
#define REG_ADO_32_L       (REG_ADO_BASE + 0x64)
#define REG_ADO_33_L       (REG_ADO_BASE + 0x66)
#define REG_ADO_34_L       (REG_ADO_BASE + 0x68)
#define REG_ADO_35_L       (REG_ADO_BASE + 0x6a)
#define REG_ADO_36_L       (REG_ADO_BASE + 0x6c)
#define REG_ADO_37_L       (REG_ADO_BASE + 0x6e)
#define REG_ADO_38_L       (REG_ADO_BASE + 0x70)
#define REG_ADO_39_L       (REG_ADO_BASE + 0x72)
#define REG_ADO_3A_L       (REG_ADO_BASE + 0x74)
#define REG_ADO_3B_L       (REG_ADO_BASE + 0x76)
#define REG_ADO_3C_L       (REG_ADO_BASE + 0x78)
#define REG_ADO_3D_L       (REG_ADO_BASE + 0x7a)
#define REG_ADO_3E_L       (REG_ADO_BASE + 0x7c)
#define REG_ADO_3F_L       (REG_ADO_BASE + 0x7e)
#define REG_ADO_40_L       (REG_ADO_BASE + 0x80)
#define REG_ADO_41_L       (REG_ADO_BASE + 0x82)
#define REG_ADO_42_L       (REG_ADO_BASE + 0x84)
#define REG_ADO_43_L       (REG_ADO_BASE + 0x86)
#define REG_ADO_44_L       (REG_ADO_BASE + 0x88)
#define REG_ADO_45_L       (REG_ADO_BASE + 0x8a)
#define REG_ADO_46_L       (REG_ADO_BASE + 0x8c)
#define REG_ADO_47_L       (REG_ADO_BASE + 0x8e)
#define REG_ADO_48_L       (REG_ADO_BASE + 0x90)
#define REG_ADO_49_L       (REG_ADO_BASE + 0x92)
#define REG_ADO_4A_L       (REG_ADO_BASE + 0x94)
#define REG_ADO_4B_L       (REG_ADO_BASE + 0x96)
#define REG_ADO_4C_L       (REG_ADO_BASE + 0x98)
#define REG_ADO_4D_L       (REG_ADO_BASE + 0x9a)
#define REG_ADO_4E_L       (REG_ADO_BASE + 0x9c)
#define REG_ADO_4F_L       (REG_ADO_BASE + 0x9e)
#define REG_ADO_50_L       (REG_ADO_BASE + 0xa0)
#define REG_ADO_51_L       (REG_ADO_BASE + 0xa2)
#define REG_ADO_52_L       (REG_ADO_BASE + 0xa4)
#define REG_ADO_53_L       (REG_ADO_BASE + 0xa6)
#define REG_ADO_54_L       (REG_ADO_BASE + 0xa8)
#define REG_ADO_55_L       (REG_ADO_BASE + 0xaa)
#define REG_ADO_56_L       (REG_ADO_BASE + 0xac)
#define REG_ADO_57_L       (REG_ADO_BASE + 0xae)
#define REG_ADO_58_L       (REG_ADO_BASE + 0xb0)
#define REG_ADO_59_L       (REG_ADO_BASE + 0xb2)
#define REG_ADO_5A_L       (REG_ADO_BASE + 0xb4)
#define REG_ADO_5B_L       (REG_ADO_BASE + 0xb6)
#define REG_ADO_5C_L       (REG_ADO_BASE + 0xb8)
#define REG_ADO_5D_L       (REG_ADO_BASE + 0xba)
#define REG_ADO_5E_L       (REG_ADO_BASE + 0xbc)
#define REG_ADO_5F_L       (REG_ADO_BASE + 0xbe)
#define REG_ADO_60_L       (REG_ADO_BASE + 0xc0)
#define REG_ADO_61_L       (REG_ADO_BASE + 0xc2)
#define REG_ADO_62_L       (REG_ADO_BASE + 0xc4)
#define REG_ADO_63_L       (REG_ADO_BASE + 0xc6)
#define REG_ADO_64_L       (REG_ADO_BASE + 0xc8)
#define REG_ADO_65_L       (REG_ADO_BASE + 0xca)
#define REG_ADO_66_L       (REG_ADO_BASE + 0xcc)
#define REG_ADO_67_L       (REG_ADO_BASE + 0xce)
#define REG_ADO_68_L       (REG_ADO_BASE + 0xd0)
#define REG_ADO_69_L       (REG_ADO_BASE + 0xd2)
#define REG_ADO_6A_L       (REG_ADO_BASE + 0xd4)
#define REG_ADO_6B_L       (REG_ADO_BASE + 0xd6)
#define REG_ADO_6C_L       (REG_ADO_BASE + 0xd8)
#define REG_ADO_6D_L       (REG_ADO_BASE + 0xda)
#define REG_ADO_6E_L       (REG_ADO_BASE + 0xdc)
#define REG_ADO_6F_L       (REG_ADO_BASE + 0xde)
#define REG_ADO_70_L       (REG_ADO_BASE + 0xe0)
#define REG_ADO_71_L       (REG_ADO_BASE + 0xe2)
#define REG_ADO_72_L       (REG_ADO_BASE + 0xe4)
#define REG_ADO_73_L       (REG_ADO_BASE + 0xe6)
#define REG_ADO_74_L       (REG_ADO_BASE + 0xe8)
#define REG_ADO_75_L       (REG_ADO_BASE + 0xea)
#define REG_ADO_76_L       (REG_ADO_BASE + 0xec)
#define REG_ADO_77_L       (REG_ADO_BASE + 0xee)
#define REG_ADO_78_L       (REG_ADO_BASE + 0xf0)
#define REG_ADO_79_L       (REG_ADO_BASE + 0xf2)
#define REG_ADO_7A_L       (REG_ADO_BASE + 0xf4)
#define REG_ADO_7B_L       (REG_ADO_BASE + 0xf6)
#define REG_ADO_7C_L       (REG_ADO_BASE + 0xf8)
#define REG_ADO_7D_L       (REG_ADO_BASE + 0xfa)
#define REG_ADO_7E_L       (REG_ADO_BASE + 0xfc)
#define REG_ADO_7F_L       (REG_ADO_BASE + 0xfe)
// h0000, bit: 7
/* checksum*/
#define offset_of_asp_cs_checksum (0x0)
#define mask_of_asp_cs_checksum   (0xff)
#define shift_of_asp_cs_checksum  (0)
#define ASP_CS_CHECKSUM           (REG_ASP_CS_BASE + offset_of_asp_cs_checksum)
#define REG_ASP_CS_00_L           (ASP_CS_CHECKSUM)
// h0000, bit: 9
/* char*/
#define offset_of_asp_cs_bPCM (0x0)
#define mask_of_asp_cs_bPCM   (0x200)
#define shift_of_asp_cs_bPCM  (9)
#define ASP_CS_BPCM           (REG_ASP_CS_BASE + offset_of_asp_cs_bPCM)
// h0001, bit: 7
/* char*/
#define offset_of_asp_cs_pk_2 (0x2)
#define mask_of_asp_cs_pk_2   (0xff)
#define shift_of_asp_cs_pk_2  (0)
#define ASP_CS_PK_2           (REG_ASP_CS_BASE + offset_of_asp_cs_pk_2)
#define REG_ASP_CS_01_L       (ASP_CS_PK_2)
// h0001, bit: 15
/* char*/
#define offset_of_asp_cs_channel_count (0x2)
#define mask_of_asp_cs_channel_count   (0xf000)
#define shift_of_asp_cs_channel_count  (12)
#define ASP_CS_CHANNEL_COUNT           (REG_ASP_CS_BASE + offset_of_asp_cs_channel_count)
// h0002, bit: 7
/* char*/
#define offset_of_asp_cs_sample_freq (0x4)
#define mask_of_asp_cs_sample_freq   (0xff)
#define shift_of_asp_cs_sample_freq  (0)
#define ASP_CS_SAMPLE_FREQ           (REG_ASP_CS_BASE + offset_of_asp_cs_sample_freq)
#define REG_ASP_CS_02_L              (ASP_CS_SAMPLE_FREQ)
// h0002, bit: 15
/* char*/
#define offset_of_asp_cs_pk_5 (0x4)
#define mask_of_asp_cs_pk_5   (0xff00)
#define shift_of_asp_cs_pk_5  (8)
#define ASP_CS_PK_5           (REG_ASP_CS_BASE + offset_of_asp_cs_pk_5)
// h0003, bit: 7
/* char*/
#define offset_of_asp_cs_pk_6 (0x6)
#define mask_of_asp_cs_pk_6   (0xff)
#define shift_of_asp_cs_pk_6  (0)
#define ASP_CS_PK_6           (REG_ASP_CS_BASE + offset_of_asp_cs_pk_6)
#define REG_ASP_CS_03_L       (ASP_CS_PK_6)
#define REG_ASP_CS_04_L       (REG_ASP_CS_BASE + 0x8)
#define REG_ASP_CS_05_L       (REG_ASP_CS_BASE + 0xa)
#define REG_ASP_CS_06_L       (REG_ASP_CS_BASE + 0xc)
#define REG_ASP_CS_07_L       (REG_ASP_CS_BASE + 0xe)
#define REG_ASP_CS_08_L       (REG_ASP_CS_BASE + 0x10)
#define REG_ASP_CS_09_L       (REG_ASP_CS_BASE + 0x12)
#define REG_ASP_CS_0A_L       (REG_ASP_CS_BASE + 0x14)
#define REG_ASP_CS_0B_L       (REG_ASP_CS_BASE + 0x16)
#define REG_ASP_CS_0C_L       (REG_ASP_CS_BASE + 0x18)
#define REG_ASP_CS_0D_L       (REG_ASP_CS_BASE + 0x1a)
#define REG_ASP_CS_0E_L       (REG_ASP_CS_BASE + 0x1c)
#define REG_ASP_CS_0F_L       (REG_ASP_CS_BASE + 0x1e)
#define REG_ASP_CS_10_L       (REG_ASP_CS_BASE + 0x20)
#define REG_ASP_CS_11_L       (REG_ASP_CS_BASE + 0x22)
#define REG_ASP_CS_12_L       (REG_ASP_CS_BASE + 0x24)
#define REG_ASP_CS_13_L       (REG_ASP_CS_BASE + 0x26)
#define REG_ASP_CS_14_L       (REG_ASP_CS_BASE + 0x28)
#define REG_ASP_CS_15_L       (REG_ASP_CS_BASE + 0x2a)
#define REG_ASP_CS_16_L       (REG_ASP_CS_BASE + 0x2c)
#define REG_ASP_CS_17_L       (REG_ASP_CS_BASE + 0x2e)
#define REG_ASP_CS_18_L       (REG_ASP_CS_BASE + 0x30)
#define REG_ASP_CS_19_L       (REG_ASP_CS_BASE + 0x32)
#define REG_ASP_CS_1A_L       (REG_ASP_CS_BASE + 0x34)
#define REG_ASP_CS_1B_L       (REG_ASP_CS_BASE + 0x36)
#define REG_ASP_CS_1C_L       (REG_ASP_CS_BASE + 0x38)
#define REG_ASP_CS_1D_L       (REG_ASP_CS_BASE + 0x3a)
#define REG_ASP_CS_1E_L       (REG_ASP_CS_BASE + 0x3c)
#define REG_ASP_CS_1F_L       (REG_ASP_CS_BASE + 0x3e)
#define REG_ASP_CS_20_L       (REG_ASP_CS_BASE + 0x40)
#define REG_ASP_CS_21_L       (REG_ASP_CS_BASE + 0x42)
#define REG_ASP_CS_22_L       (REG_ASP_CS_BASE + 0x44)
#define REG_ASP_CS_23_L       (REG_ASP_CS_BASE + 0x46)
#define REG_ASP_CS_24_L       (REG_ASP_CS_BASE + 0x48)
#define REG_ASP_CS_25_L       (REG_ASP_CS_BASE + 0x4a)
#define REG_ASP_CS_26_L       (REG_ASP_CS_BASE + 0x4c)
#define REG_ASP_CS_27_L       (REG_ASP_CS_BASE + 0x4e)
#define REG_ASP_CS_28_L       (REG_ASP_CS_BASE + 0x50)
#define REG_ASP_CS_29_L       (REG_ASP_CS_BASE + 0x52)
#define REG_ASP_CS_2A_L       (REG_ASP_CS_BASE + 0x54)
#define REG_ASP_CS_2B_L       (REG_ASP_CS_BASE + 0x56)
#define REG_ASP_CS_2C_L       (REG_ASP_CS_BASE + 0x58)
#define REG_ASP_CS_2D_L       (REG_ASP_CS_BASE + 0x5a)
#define REG_ASP_CS_2E_L       (REG_ASP_CS_BASE + 0x5c)
#define REG_ASP_CS_2F_L       (REG_ASP_CS_BASE + 0x5e)
#define REG_ASP_CS_30_L       (REG_ASP_CS_BASE + 0x60)
#define REG_ASP_CS_31_L       (REG_ASP_CS_BASE + 0x62)
#define REG_ASP_CS_32_L       (REG_ASP_CS_BASE + 0x64)
#define REG_ASP_CS_33_L       (REG_ASP_CS_BASE + 0x66)
#define REG_ASP_CS_34_L       (REG_ASP_CS_BASE + 0x68)
#define REG_ASP_CS_35_L       (REG_ASP_CS_BASE + 0x6a)
#define REG_ASP_CS_36_L       (REG_ASP_CS_BASE + 0x6c)
#define REG_ASP_CS_37_L       (REG_ASP_CS_BASE + 0x6e)
#define REG_ASP_CS_38_L       (REG_ASP_CS_BASE + 0x70)
#define REG_ASP_CS_39_L       (REG_ASP_CS_BASE + 0x72)
#define REG_ASP_CS_3A_L       (REG_ASP_CS_BASE + 0x74)
#define REG_ASP_CS_3B_L       (REG_ASP_CS_BASE + 0x76)
#define REG_ASP_CS_3C_L       (REG_ASP_CS_BASE + 0x78)
#define REG_ASP_CS_3D_L       (REG_ASP_CS_BASE + 0x7a)
#define REG_ASP_CS_3E_L       (REG_ASP_CS_BASE + 0x7c)
#define REG_ASP_CS_3F_L       (REG_ASP_CS_BASE + 0x7e)
#define REG_ASP_CS_40_L       (REG_ASP_CS_BASE + 0x80)
#define REG_ASP_CS_41_L       (REG_ASP_CS_BASE + 0x82)
#define REG_ASP_CS_42_L       (REG_ASP_CS_BASE + 0x84)
#define REG_ASP_CS_43_L       (REG_ASP_CS_BASE + 0x86)
#define REG_ASP_CS_44_L       (REG_ASP_CS_BASE + 0x88)
#define REG_ASP_CS_45_L       (REG_ASP_CS_BASE + 0x8a)
#define REG_ASP_CS_46_L       (REG_ASP_CS_BASE + 0x8c)
#define REG_ASP_CS_47_L       (REG_ASP_CS_BASE + 0x8e)
#define REG_ASP_CS_48_L       (REG_ASP_CS_BASE + 0x90)
#define REG_ASP_CS_49_L       (REG_ASP_CS_BASE + 0x92)
#define REG_ASP_CS_4A_L       (REG_ASP_CS_BASE + 0x94)
#define REG_ASP_CS_4B_L       (REG_ASP_CS_BASE + 0x96)
#define REG_ASP_CS_4C_L       (REG_ASP_CS_BASE + 0x98)
#define REG_ASP_CS_4D_L       (REG_ASP_CS_BASE + 0x9a)
#define REG_ASP_CS_4E_L       (REG_ASP_CS_BASE + 0x9c)
#define REG_ASP_CS_4F_L       (REG_ASP_CS_BASE + 0x9e)
#define REG_ASP_CS_50_L       (REG_ASP_CS_BASE + 0xa0)
#define REG_ASP_CS_51_L       (REG_ASP_CS_BASE + 0xa2)
#define REG_ASP_CS_52_L       (REG_ASP_CS_BASE + 0xa4)
#define REG_ASP_CS_53_L       (REG_ASP_CS_BASE + 0xa6)
#define REG_ASP_CS_54_L       (REG_ASP_CS_BASE + 0xa8)
#define REG_ASP_CS_55_L       (REG_ASP_CS_BASE + 0xaa)
#define REG_ASP_CS_56_L       (REG_ASP_CS_BASE + 0xac)
#define REG_ASP_CS_57_L       (REG_ASP_CS_BASE + 0xae)
#define REG_ASP_CS_58_L       (REG_ASP_CS_BASE + 0xb0)
#define REG_ASP_CS_59_L       (REG_ASP_CS_BASE + 0xb2)
#define REG_ASP_CS_5A_L       (REG_ASP_CS_BASE + 0xb4)
#define REG_ASP_CS_5B_L       (REG_ASP_CS_BASE + 0xb6)
#define REG_ASP_CS_5C_L       (REG_ASP_CS_BASE + 0xb8)
#define REG_ASP_CS_5D_L       (REG_ASP_CS_BASE + 0xba)
#define REG_ASP_CS_5E_L       (REG_ASP_CS_BASE + 0xbc)
#define REG_ASP_CS_5F_L       (REG_ASP_CS_BASE + 0xbe)
#define REG_ASP_CS_60_L       (REG_ASP_CS_BASE + 0xc0)
#define REG_ASP_CS_61_L       (REG_ASP_CS_BASE + 0xc2)
#define REG_ASP_CS_62_L       (REG_ASP_CS_BASE + 0xc4)
#define REG_ASP_CS_63_L       (REG_ASP_CS_BASE + 0xc6)
#define REG_ASP_CS_64_L       (REG_ASP_CS_BASE + 0xc8)
#define REG_ASP_CS_65_L       (REG_ASP_CS_BASE + 0xca)
#define REG_ASP_CS_66_L       (REG_ASP_CS_BASE + 0xcc)
#define REG_ASP_CS_67_L       (REG_ASP_CS_BASE + 0xce)
#define REG_ASP_CS_68_L       (REG_ASP_CS_BASE + 0xd0)
#define REG_ASP_CS_69_L       (REG_ASP_CS_BASE + 0xd2)
#define REG_ASP_CS_6A_L       (REG_ASP_CS_BASE + 0xd4)
#define REG_ASP_CS_6B_L       (REG_ASP_CS_BASE + 0xd6)
#define REG_ASP_CS_6C_L       (REG_ASP_CS_BASE + 0xd8)
#define REG_ASP_CS_6D_L       (REG_ASP_CS_BASE + 0xda)
#define REG_ASP_CS_6E_L       (REG_ASP_CS_BASE + 0xdc)
#define REG_ASP_CS_6F_L       (REG_ASP_CS_BASE + 0xde)
#define REG_ASP_CS_70_L       (REG_ASP_CS_BASE + 0xe0)
#define REG_ASP_CS_71_L       (REG_ASP_CS_BASE + 0xe2)
#define REG_ASP_CS_72_L       (REG_ASP_CS_BASE + 0xe4)
#define REG_ASP_CS_73_L       (REG_ASP_CS_BASE + 0xe6)
#define REG_ASP_CS_74_L       (REG_ASP_CS_BASE + 0xe8)
#define REG_ASP_CS_75_L       (REG_ASP_CS_BASE + 0xea)
#define REG_ASP_CS_76_L       (REG_ASP_CS_BASE + 0xec)
#define REG_ASP_CS_77_L       (REG_ASP_CS_BASE + 0xee)
#define REG_ASP_CS_78_L       (REG_ASP_CS_BASE + 0xf0)
#define REG_ASP_CS_79_L       (REG_ASP_CS_BASE + 0xf2)
#define REG_ASP_CS_7A_L       (REG_ASP_CS_BASE + 0xf4)
#define REG_ASP_CS_7B_L       (REG_ASP_CS_BASE + 0xf6)
#define REG_ASP_CS_7C_L       (REG_ASP_CS_BASE + 0xf8)
#define REG_ASP_CS_7D_L       (REG_ASP_CS_BASE + 0xfa)
#define REG_ASP_CS_7E_L       (REG_ASP_CS_BASE + 0xfc)
#define REG_ASP_CS_7F_L       (REG_ASP_CS_BASE + 0xfe)
// h0000, bit: 7
/* infoframe type =0x83*/
#define offset_of_spd_hd_infoframe_type_code (0x0)
#define mask_of_spd_hd_infoframe_type_code   (0xff)
#define shift_of_spd_hd_infoframe_type_code  (0)
#define SPD_HD_INFOFRAME_TYPE_CODE           (REG_SPD_HD_BASE + offset_of_spd_hd_infoframe_type_code)
#define REG_SPD_HD_00_L                      (SPD_HD_INFOFRAME_TYPE_CODE)
// h0000, bit: 15
/* version = 0x1*/
#define offset_of_spd_hd_infoframe_version_number (0x0)
#define mask_of_spd_hd_infoframe_version_number   (0xff00)
#define shift_of_spd_hd_infoframe_version_number  (8)
#define SPD_HD_INFOFRAME_VERSION_NUMBER           (REG_SPD_HD_BASE + offset_of_spd_hd_infoframe_version_number)
// h0001, bit: 7
/* length = 25*/
#define offset_of_spd_hd_length_of_SPD (0x2)
#define mask_of_spd_hd_length_of_SPD   (0xff)
#define shift_of_spd_hd_length_of_SPD  (0)
#define SPD_HD_LENGTH_OF_SPD           (REG_SPD_HD_BASE + offset_of_spd_hd_length_of_SPD)
#define REG_SPD_HD_01_L                (SPD_HD_LENGTH_OF_SPD)
#define REG_SPD_HD_02_L                (REG_SPD_HD_BASE + 0x4)
#define REG_SPD_HD_03_L                (REG_SPD_HD_BASE + 0x6)
#define REG_SPD_HD_04_L                (REG_SPD_HD_BASE + 0x8)
#define REG_SPD_HD_05_L                (REG_SPD_HD_BASE + 0xa)
#define REG_SPD_HD_06_L                (REG_SPD_HD_BASE + 0xc)
#define REG_SPD_HD_07_L                (REG_SPD_HD_BASE + 0xe)
#define REG_SPD_HD_08_L                (REG_SPD_HD_BASE + 0x10)
#define REG_SPD_HD_09_L                (REG_SPD_HD_BASE + 0x12)
#define REG_SPD_HD_0A_L                (REG_SPD_HD_BASE + 0x14)
#define REG_SPD_HD_0B_L                (REG_SPD_HD_BASE + 0x16)
#define REG_SPD_HD_0C_L                (REG_SPD_HD_BASE + 0x18)
#define REG_SPD_HD_0D_L                (REG_SPD_HD_BASE + 0x1a)
#define REG_SPD_HD_0E_L                (REG_SPD_HD_BASE + 0x1c)
#define REG_SPD_HD_0F_L                (REG_SPD_HD_BASE + 0x1e)
#define REG_SPD_HD_10_L                (REG_SPD_HD_BASE + 0x20)
#define REG_SPD_HD_11_L                (REG_SPD_HD_BASE + 0x22)
#define REG_SPD_HD_12_L                (REG_SPD_HD_BASE + 0x24)
#define REG_SPD_HD_13_L                (REG_SPD_HD_BASE + 0x26)
#define REG_SPD_HD_14_L                (REG_SPD_HD_BASE + 0x28)
#define REG_SPD_HD_15_L                (REG_SPD_HD_BASE + 0x2a)
#define REG_SPD_HD_16_L                (REG_SPD_HD_BASE + 0x2c)
#define REG_SPD_HD_17_L                (REG_SPD_HD_BASE + 0x2e)
#define REG_SPD_HD_18_L                (REG_SPD_HD_BASE + 0x30)
#define REG_SPD_HD_19_L                (REG_SPD_HD_BASE + 0x32)
#define REG_SPD_HD_1A_L                (REG_SPD_HD_BASE + 0x34)
#define REG_SPD_HD_1B_L                (REG_SPD_HD_BASE + 0x36)
#define REG_SPD_HD_1C_L                (REG_SPD_HD_BASE + 0x38)
#define REG_SPD_HD_1D_L                (REG_SPD_HD_BASE + 0x3a)
#define REG_SPD_HD_1E_L                (REG_SPD_HD_BASE + 0x3c)
#define REG_SPD_HD_1F_L                (REG_SPD_HD_BASE + 0x3e)
#define REG_SPD_HD_20_L                (REG_SPD_HD_BASE + 0x40)
#define REG_SPD_HD_21_L                (REG_SPD_HD_BASE + 0x42)
#define REG_SPD_HD_22_L                (REG_SPD_HD_BASE + 0x44)
#define REG_SPD_HD_23_L                (REG_SPD_HD_BASE + 0x46)
#define REG_SPD_HD_24_L                (REG_SPD_HD_BASE + 0x48)
#define REG_SPD_HD_25_L                (REG_SPD_HD_BASE + 0x4a)
#define REG_SPD_HD_26_L                (REG_SPD_HD_BASE + 0x4c)
#define REG_SPD_HD_27_L                (REG_SPD_HD_BASE + 0x4e)
#define REG_SPD_HD_28_L                (REG_SPD_HD_BASE + 0x50)
#define REG_SPD_HD_29_L                (REG_SPD_HD_BASE + 0x52)
#define REG_SPD_HD_2A_L                (REG_SPD_HD_BASE + 0x54)
#define REG_SPD_HD_2B_L                (REG_SPD_HD_BASE + 0x56)
#define REG_SPD_HD_2C_L                (REG_SPD_HD_BASE + 0x58)
#define REG_SPD_HD_2D_L                (REG_SPD_HD_BASE + 0x5a)
#define REG_SPD_HD_2E_L                (REG_SPD_HD_BASE + 0x5c)
#define REG_SPD_HD_2F_L                (REG_SPD_HD_BASE + 0x5e)
#define REG_SPD_HD_30_L                (REG_SPD_HD_BASE + 0x60)
#define REG_SPD_HD_31_L                (REG_SPD_HD_BASE + 0x62)
#define REG_SPD_HD_32_L                (REG_SPD_HD_BASE + 0x64)
#define REG_SPD_HD_33_L                (REG_SPD_HD_BASE + 0x66)
#define REG_SPD_HD_34_L                (REG_SPD_HD_BASE + 0x68)
#define REG_SPD_HD_35_L                (REG_SPD_HD_BASE + 0x6a)
#define REG_SPD_HD_36_L                (REG_SPD_HD_BASE + 0x6c)
#define REG_SPD_HD_37_L                (REG_SPD_HD_BASE + 0x6e)
#define REG_SPD_HD_38_L                (REG_SPD_HD_BASE + 0x70)
#define REG_SPD_HD_39_L                (REG_SPD_HD_BASE + 0x72)
#define REG_SPD_HD_3A_L                (REG_SPD_HD_BASE + 0x74)
#define REG_SPD_HD_3B_L                (REG_SPD_HD_BASE + 0x76)
#define REG_SPD_HD_3C_L                (REG_SPD_HD_BASE + 0x78)
#define REG_SPD_HD_3D_L                (REG_SPD_HD_BASE + 0x7a)
#define REG_SPD_HD_3E_L                (REG_SPD_HD_BASE + 0x7c)
#define REG_SPD_HD_3F_L                (REG_SPD_HD_BASE + 0x7e)
#define REG_SPD_HD_40_L                (REG_SPD_HD_BASE + 0x80)
#define REG_SPD_HD_41_L                (REG_SPD_HD_BASE + 0x82)
#define REG_SPD_HD_42_L                (REG_SPD_HD_BASE + 0x84)
#define REG_SPD_HD_43_L                (REG_SPD_HD_BASE + 0x86)
#define REG_SPD_HD_44_L                (REG_SPD_HD_BASE + 0x88)
#define REG_SPD_HD_45_L                (REG_SPD_HD_BASE + 0x8a)
#define REG_SPD_HD_46_L                (REG_SPD_HD_BASE + 0x8c)
#define REG_SPD_HD_47_L                (REG_SPD_HD_BASE + 0x8e)
#define REG_SPD_HD_48_L                (REG_SPD_HD_BASE + 0x90)
#define REG_SPD_HD_49_L                (REG_SPD_HD_BASE + 0x92)
#define REG_SPD_HD_4A_L                (REG_SPD_HD_BASE + 0x94)
#define REG_SPD_HD_4B_L                (REG_SPD_HD_BASE + 0x96)
#define REG_SPD_HD_4C_L                (REG_SPD_HD_BASE + 0x98)
#define REG_SPD_HD_4D_L                (REG_SPD_HD_BASE + 0x9a)
#define REG_SPD_HD_4E_L                (REG_SPD_HD_BASE + 0x9c)
#define REG_SPD_HD_4F_L                (REG_SPD_HD_BASE + 0x9e)
#define REG_SPD_HD_50_L                (REG_SPD_HD_BASE + 0xa0)
#define REG_SPD_HD_51_L                (REG_SPD_HD_BASE + 0xa2)
#define REG_SPD_HD_52_L                (REG_SPD_HD_BASE + 0xa4)
#define REG_SPD_HD_53_L                (REG_SPD_HD_BASE + 0xa6)
#define REG_SPD_HD_54_L                (REG_SPD_HD_BASE + 0xa8)
#define REG_SPD_HD_55_L                (REG_SPD_HD_BASE + 0xaa)
#define REG_SPD_HD_56_L                (REG_SPD_HD_BASE + 0xac)
#define REG_SPD_HD_57_L                (REG_SPD_HD_BASE + 0xae)
#define REG_SPD_HD_58_L                (REG_SPD_HD_BASE + 0xb0)
#define REG_SPD_HD_59_L                (REG_SPD_HD_BASE + 0xb2)
#define REG_SPD_HD_5A_L                (REG_SPD_HD_BASE + 0xb4)
#define REG_SPD_HD_5B_L                (REG_SPD_HD_BASE + 0xb6)
#define REG_SPD_HD_5C_L                (REG_SPD_HD_BASE + 0xb8)
#define REG_SPD_HD_5D_L                (REG_SPD_HD_BASE + 0xba)
#define REG_SPD_HD_5E_L                (REG_SPD_HD_BASE + 0xbc)
#define REG_SPD_HD_5F_L                (REG_SPD_HD_BASE + 0xbe)
#define REG_SPD_HD_60_L                (REG_SPD_HD_BASE + 0xc0)
#define REG_SPD_HD_61_L                (REG_SPD_HD_BASE + 0xc2)
#define REG_SPD_HD_62_L                (REG_SPD_HD_BASE + 0xc4)
#define REG_SPD_HD_63_L                (REG_SPD_HD_BASE + 0xc6)
#define REG_SPD_HD_64_L                (REG_SPD_HD_BASE + 0xc8)
#define REG_SPD_HD_65_L                (REG_SPD_HD_BASE + 0xca)
#define REG_SPD_HD_66_L                (REG_SPD_HD_BASE + 0xcc)
#define REG_SPD_HD_67_L                (REG_SPD_HD_BASE + 0xce)
#define REG_SPD_HD_68_L                (REG_SPD_HD_BASE + 0xd0)
#define REG_SPD_HD_69_L                (REG_SPD_HD_BASE + 0xd2)
#define REG_SPD_HD_6A_L                (REG_SPD_HD_BASE + 0xd4)
#define REG_SPD_HD_6B_L                (REG_SPD_HD_BASE + 0xd6)
#define REG_SPD_HD_6C_L                (REG_SPD_HD_BASE + 0xd8)
#define REG_SPD_HD_6D_L                (REG_SPD_HD_BASE + 0xda)
#define REG_SPD_HD_6E_L                (REG_SPD_HD_BASE + 0xdc)
#define REG_SPD_HD_6F_L                (REG_SPD_HD_BASE + 0xde)
#define REG_SPD_HD_70_L                (REG_SPD_HD_BASE + 0xe0)
#define REG_SPD_HD_71_L                (REG_SPD_HD_BASE + 0xe2)
#define REG_SPD_HD_72_L                (REG_SPD_HD_BASE + 0xe4)
#define REG_SPD_HD_73_L                (REG_SPD_HD_BASE + 0xe6)
#define REG_SPD_HD_74_L                (REG_SPD_HD_BASE + 0xe8)
#define REG_SPD_HD_75_L                (REG_SPD_HD_BASE + 0xea)
#define REG_SPD_HD_76_L                (REG_SPD_HD_BASE + 0xec)
#define REG_SPD_HD_77_L                (REG_SPD_HD_BASE + 0xee)
#define REG_SPD_HD_78_L                (REG_SPD_HD_BASE + 0xf0)
#define REG_SPD_HD_79_L                (REG_SPD_HD_BASE + 0xf2)
#define REG_SPD_HD_7A_L                (REG_SPD_HD_BASE + 0xf4)
#define REG_SPD_HD_7B_L                (REG_SPD_HD_BASE + 0xf6)
#define REG_SPD_HD_7C_L                (REG_SPD_HD_BASE + 0xf8)
#define REG_SPD_HD_7D_L                (REG_SPD_HD_BASE + 0xfa)
#define REG_SPD_HD_7E_L                (REG_SPD_HD_BASE + 0xfc)
#define REG_SPD_HD_7F_L                (REG_SPD_HD_BASE + 0xfe)
// h0000, bit: 7
/* checksum*/
#define offset_of_spd_checksum (0x0)
#define mask_of_spd_checksum   (0xff)
#define shift_of_spd_checksum  (0)
#define SPD_CHECKSUM           (REG_SPD_BASE + offset_of_spd_checksum)
#define REG_SPD_00_L           (SPD_CHECKSUM)
// h0000, bit: 15
/* char*/
#define offset_of_spd_vendor_name_char_0 (0x0)
#define mask_of_spd_vendor_name_char_0   (0xff00)
#define shift_of_spd_vendor_name_char_0  (8)
#define SPD_VENDOR_NAME_CHAR_0           (REG_SPD_BASE + offset_of_spd_vendor_name_char_0)
// h0001, bit: 7
/* char*/
#define offset_of_spd_vendor_name_char_1 (0x2)
#define mask_of_spd_vendor_name_char_1   (0xff)
#define shift_of_spd_vendor_name_char_1  (0)
#define SPD_VENDOR_NAME_CHAR_1           (REG_SPD_BASE + offset_of_spd_vendor_name_char_1)
#define REG_SPD_01_L                     (SPD_VENDOR_NAME_CHAR_1)
// h0001, bit: 15
/* char*/
#define offset_of_spd_vendor_name_char_2 (0x2)
#define mask_of_spd_vendor_name_char_2   (0xff00)
#define shift_of_spd_vendor_name_char_2  (8)
#define SPD_VENDOR_NAME_CHAR_2           (REG_SPD_BASE + offset_of_spd_vendor_name_char_2)
// h0002, bit: 7
/* char*/
#define offset_of_spd_vendor_name_char_3 (0x4)
#define mask_of_spd_vendor_name_char_3   (0xff)
#define shift_of_spd_vendor_name_char_3  (0)
#define SPD_VENDOR_NAME_CHAR_3           (REG_SPD_BASE + offset_of_spd_vendor_name_char_3)
#define REG_SPD_02_L                     (SPD_VENDOR_NAME_CHAR_3)
// h0002, bit: 15
/* char*/
#define offset_of_spd_vendor_name_char_4 (0x4)
#define mask_of_spd_vendor_name_char_4   (0xff00)
#define shift_of_spd_vendor_name_char_4  (8)
#define SPD_VENDOR_NAME_CHAR_4           (REG_SPD_BASE + offset_of_spd_vendor_name_char_4)
// h0003, bit: 7
/* char*/
#define offset_of_spd_vendor_name_char_5 (0x6)
#define mask_of_spd_vendor_name_char_5   (0xff)
#define shift_of_spd_vendor_name_char_5  (0)
#define SPD_VENDOR_NAME_CHAR_5           (REG_SPD_BASE + offset_of_spd_vendor_name_char_5)
#define REG_SPD_03_L                     (SPD_VENDOR_NAME_CHAR_5)
// h0003, bit: 15
/* char*/
#define offset_of_spd_ecc_0 (0x6)
#define mask_of_spd_ecc_0 (0xff00)
#define shift_of_spd_ecc_0 (8)
#define SPD_ECC_0 (REG_SPD_BASE + offset_of_spd_ecc_0)
#define offset_of_spd_vendor_name_char_6 (0x8)
#define mask_of_spd_vendor_name_char_6 (0xff)
#define shift_of_spd_vendor_name_char_6 (0)
#define SPD_VENDOR_NAME_CHAR_6           (REG_SPD_BASE + offset_of_spd_vendor_name_char_6)
#define REG_SPD_04_L (SPD_VENDOR_NAME_CHAR_6)
// h0004, bit: 7
/* char*/
#define offset_of_spd_vendor_name_char_7 (0x8)
#define mask_of_spd_vendor_name_char_7 (0xff00)
#define shift_of_spd_vendor_name_char_7 (8)
#define SPD_VENDOR_NAME_CHAR_7           (REG_SPD_BASE + offset_of_spd_vendor_name_char_7)
// h0004, bit: 15
/* char*/
#define offset_of_spd_procduct_des_char_0 (0xa)
#define mask_of_spd_procduct_des_char_0 (0xff)
#define shift_of_spd_procduct_des_char_0 (0)
#define SPD_PROCDUCT_DES_CHAR_0           (REG_SPD_BASE + offset_of_spd_procduct_des_char_0)
#define REG_SPD_05_L (SPD_PROCDUCT_DES_CHAR_0)
// h0005, bit: 7
/* char*/
#define offset_of_spd_procduct_des_char_1 (0xa)
#define mask_of_spd_procduct_des_char_1 (0xff00)
#define shift_of_spd_procduct_des_char_1 (8)
#define SPD_PROCDUCT_DES_CHAR_1           (REG_SPD_BASE + offset_of_spd_procduct_des_char_1)
// h0005, bit: 15
/* char*/
#define offset_of_spd_procduct_des_char_2 (0xc)
#define mask_of_spd_procduct_des_char_2 (0xff)
#define shift_of_spd_procduct_des_char_2 (0)
#define SPD_PROCDUCT_DES_CHAR_2           (REG_SPD_BASE + offset_of_spd_procduct_des_char_2)
#define REG_SPD_06_L (SPD_PROCDUCT_DES_CHAR_2)
// h0006, bit: 7
/* char*/
#define offset_of_spd_procduct_des_char_3 (0xc)
#define mask_of_spd_procduct_des_char_3 (0xff00)
#define shift_of_spd_procduct_des_char_3 (8)
#define SPD_PROCDUCT_DES_CHAR_3           (REG_SPD_BASE + offset_of_spd_procduct_des_char_3)
// h0006, bit: 15
/* char*/
// h0007, bit: 7
/* char*/
#define offset_of_spd_procduct_des_char_5 (0xe)
#define mask_of_spd_procduct_des_char_5   (0xff)
#define shift_of_spd_procduct_des_char_5  (0)
#define SPD_PROCDUCT_DES_CHAR_5           (REG_SPD_BASE + offset_of_spd_procduct_des_char_5)
#define REG_SPD_07_L                      (SPD_PROCDUCT_DES_CHAR_5)
// h0007, bit: 15
/* char*/
#define offset_of_spd_ecc_1 (0xe)
#define mask_of_spd_ecc_1 (0xff00)
#define shift_of_spd_ecc_1 (8)
#define SPD_ECC_1 (REG_SPD_BASE + offset_of_spd_ecc_1)
// h0008, bit: 7
/* char*/
#define offset_of_spd_procduct_des_char_7 (0x10)
#define mask_of_spd_procduct_des_char_7   (0xff)
#define shift_of_spd_procduct_des_char_7  (0)
#define SPD_PROCDUCT_DES_CHAR_7           (REG_SPD_BASE + offset_of_spd_procduct_des_char_7)
#define REG_SPD_08_L                      (SPD_PROCDUCT_DES_CHAR_7)
// h0008, bit: 15
/* char*/
#define offset_of_spd_procduct_des_char_6 (0x10)
#define mask_of_spd_procduct_des_char_6 (0xff00)
#define shift_of_spd_procduct_des_char_6 (8)
#define SPD_PROCDUCT_DES_CHAR_6 (REG_SPD_BASE + offset_of_spd_procduct_des_char_6)
#define offset_of_spd_procduct_des_char_8 (0x12)
#define mask_of_spd_procduct_des_char_8   (0xff00)
#define shift_of_spd_procduct_des_char_8  (8)
#define SPD_PROCDUCT_DES_CHAR_8           (REG_SPD_BASE + offset_of_spd_procduct_des_char_8)
#define REG_SPD_09_L (SPD_PROCDUCT_DES_CHAR_8)
// h0009, bit: 7
/* char*/
#define offset_of_spd_procduct_des_char_9 (0x14)
#define mask_of_spd_procduct_des_char_9   (0xff)
#define shift_of_spd_procduct_des_char_9  (0)
#define SPD_PROCDUCT_DES_CHAR_9           (REG_SPD_BASE + offset_of_spd_procduct_des_char_9)
#define REG_SPD_0A_L (SPD_PROCDUCT_DES_CHAR_9)
// h0009, bit: 15
/* char*/
#define offset_of_spd_procduct_des_char_10 (0x14)
#define mask_of_spd_procduct_des_char_10   (0xff00)
#define shift_of_spd_procduct_des_char_10  (8)
#define SPD_PROCDUCT_DES_CHAR_10           (REG_SPD_BASE + offset_of_spd_procduct_des_char_10)
// h000a, bit: 7
/* char*/
#define offset_of_spd_procduct_des_char_11 (0x16)
#define mask_of_spd_procduct_des_char_11   (0xff)
#define shift_of_spd_procduct_des_char_11  (0)
#define SPD_PROCDUCT_DES_CHAR_11           (REG_SPD_BASE + offset_of_spd_procduct_des_char_11)
#define REG_SPD_0B_L (SPD_PROCDUCT_DES_CHAR_11)
// h000a, bit: 15
/* char*/
#define offset_of_spd_ecc_2 (0x16)
#define mask_of_spd_ecc_2 (0xff00)
#define shift_of_spd_ecc_2 (8)
#define SPD_ECC_2 (REG_SPD_BASE + offset_of_spd_ecc_2)
#define offset_of_spd_procduct_des_char_12 (0x18)
#define mask_of_spd_procduct_des_char_12 (0xff)
#define shift_of_spd_procduct_des_char_12 (0)
#define SPD_PROCDUCT_DES_CHAR_12           (REG_SPD_BASE + offset_of_spd_procduct_des_char_12)
#define REG_SPD_0C_L (SPD_PROCDUCT_DES_CHAR_12)
// h000b, bit: 7
/* char*/
#define offset_of_spd_procduct_des_char_13 (0x18)
#define mask_of_spd_procduct_des_char_13 (0xff00)
#define shift_of_spd_procduct_des_char_13 (8)
#define SPD_PROCDUCT_DES_CHAR_13           (REG_SPD_BASE + offset_of_spd_procduct_des_char_13)
// h000b, bit: 15
/* char*/
#define offset_of_spd_procduct_des_char_14 (0x1a)
#define mask_of_spd_procduct_des_char_14 (0xff)
#define shift_of_spd_procduct_des_char_14 (0)
#define SPD_PROCDUCT_DES_CHAR_14           (REG_SPD_BASE + offset_of_spd_procduct_des_char_14)
#define REG_SPD_0D_L (SPD_PROCDUCT_DES_CHAR_14)
// h000c, bit: 7
/* char*/
#define offset_of_spd_procduct_des_char_15 (0x1a)
#define mask_of_spd_procduct_des_char_15 (0xff00)
#define shift_of_spd_procduct_des_char_15 (8)
#define SPD_PROCDUCT_DES_CHAR_15           (REG_SPD_BASE + offset_of_spd_procduct_des_char_15)
// h000c, bit: 15
/* HDMITX_PACKET_SPD_SDI = 1U*/
#define offset_of_spd_source_info (0x1c)
#define mask_of_spd_source_info (0xff)
#define shift_of_spd_source_info (0)
#define SPD_SOURCE_INFO           (REG_SPD_BASE + offset_of_spd_source_info)
#define REG_SPD_0E_L (SPD_SOURCE_INFO)
#define REG_SPD_0F_L              (REG_SPD_BASE + 0x1e)
#define REG_SPD_10_L              (REG_SPD_BASE + 0x20)
#define REG_SPD_11_L              (REG_SPD_BASE + 0x22)
#define REG_SPD_12_L              (REG_SPD_BASE + 0x24)
#define REG_SPD_13_L              (REG_SPD_BASE + 0x26)
#define REG_SPD_14_L              (REG_SPD_BASE + 0x28)
#define REG_SPD_15_L              (REG_SPD_BASE + 0x2a)
#define REG_SPD_16_L              (REG_SPD_BASE + 0x2c)
#define REG_SPD_17_L              (REG_SPD_BASE + 0x2e)
#define REG_SPD_18_L              (REG_SPD_BASE + 0x30)
#define REG_SPD_19_L              (REG_SPD_BASE + 0x32)
#define REG_SPD_1A_L              (REG_SPD_BASE + 0x34)
#define REG_SPD_1B_L              (REG_SPD_BASE + 0x36)
#define REG_SPD_1C_L              (REG_SPD_BASE + 0x38)
#define REG_SPD_1D_L              (REG_SPD_BASE + 0x3a)
#define REG_SPD_1E_L              (REG_SPD_BASE + 0x3c)
#define REG_SPD_1F_L              (REG_SPD_BASE + 0x3e)
#define REG_SPD_20_L              (REG_SPD_BASE + 0x40)
#define REG_SPD_21_L              (REG_SPD_BASE + 0x42)
#define REG_SPD_22_L              (REG_SPD_BASE + 0x44)
#define REG_SPD_23_L              (REG_SPD_BASE + 0x46)
#define REG_SPD_24_L              (REG_SPD_BASE + 0x48)
#define REG_SPD_25_L              (REG_SPD_BASE + 0x4a)
#define REG_SPD_26_L              (REG_SPD_BASE + 0x4c)
#define REG_SPD_27_L              (REG_SPD_BASE + 0x4e)
#define REG_SPD_28_L              (REG_SPD_BASE + 0x50)
#define REG_SPD_29_L              (REG_SPD_BASE + 0x52)
#define REG_SPD_2A_L              (REG_SPD_BASE + 0x54)
#define REG_SPD_2B_L              (REG_SPD_BASE + 0x56)
#define REG_SPD_2C_L              (REG_SPD_BASE + 0x58)
#define REG_SPD_2D_L              (REG_SPD_BASE + 0x5a)
#define REG_SPD_2E_L              (REG_SPD_BASE + 0x5c)
#define REG_SPD_2F_L              (REG_SPD_BASE + 0x5e)
#define REG_SPD_30_L              (REG_SPD_BASE + 0x60)
#define REG_SPD_31_L              (REG_SPD_BASE + 0x62)
#define REG_SPD_32_L              (REG_SPD_BASE + 0x64)
#define REG_SPD_33_L              (REG_SPD_BASE + 0x66)
#define REG_SPD_34_L              (REG_SPD_BASE + 0x68)
#define REG_SPD_35_L              (REG_SPD_BASE + 0x6a)
#define REG_SPD_36_L              (REG_SPD_BASE + 0x6c)
#define REG_SPD_37_L              (REG_SPD_BASE + 0x6e)
#define REG_SPD_38_L              (REG_SPD_BASE + 0x70)
#define REG_SPD_39_L              (REG_SPD_BASE + 0x72)
#define REG_SPD_3A_L              (REG_SPD_BASE + 0x74)
#define REG_SPD_3B_L              (REG_SPD_BASE + 0x76)
#define REG_SPD_3C_L              (REG_SPD_BASE + 0x78)
#define REG_SPD_3D_L              (REG_SPD_BASE + 0x7a)
#define REG_SPD_3E_L              (REG_SPD_BASE + 0x7c)
#define REG_SPD_3F_L              (REG_SPD_BASE + 0x7e)
#define REG_SPD_40_L              (REG_SPD_BASE + 0x80)
#define REG_SPD_41_L              (REG_SPD_BASE + 0x82)
#define REG_SPD_42_L              (REG_SPD_BASE + 0x84)
#define REG_SPD_43_L              (REG_SPD_BASE + 0x86)
#define REG_SPD_44_L              (REG_SPD_BASE + 0x88)
#define REG_SPD_45_L              (REG_SPD_BASE + 0x8a)
#define REG_SPD_46_L              (REG_SPD_BASE + 0x8c)
#define REG_SPD_47_L              (REG_SPD_BASE + 0x8e)
#define REG_SPD_48_L              (REG_SPD_BASE + 0x90)
#define REG_SPD_49_L              (REG_SPD_BASE + 0x92)
#define REG_SPD_4A_L              (REG_SPD_BASE + 0x94)
#define REG_SPD_4B_L              (REG_SPD_BASE + 0x96)
#define REG_SPD_4C_L              (REG_SPD_BASE + 0x98)
#define REG_SPD_4D_L              (REG_SPD_BASE + 0x9a)
#define REG_SPD_4E_L              (REG_SPD_BASE + 0x9c)
#define REG_SPD_4F_L              (REG_SPD_BASE + 0x9e)
#define REG_SPD_50_L              (REG_SPD_BASE + 0xa0)
#define REG_SPD_51_L              (REG_SPD_BASE + 0xa2)
#define REG_SPD_52_L              (REG_SPD_BASE + 0xa4)
#define REG_SPD_53_L              (REG_SPD_BASE + 0xa6)
#define REG_SPD_54_L              (REG_SPD_BASE + 0xa8)
#define REG_SPD_55_L              (REG_SPD_BASE + 0xaa)
#define REG_SPD_56_L              (REG_SPD_BASE + 0xac)
#define REG_SPD_57_L              (REG_SPD_BASE + 0xae)
#define REG_SPD_58_L              (REG_SPD_BASE + 0xb0)
#define REG_SPD_59_L              (REG_SPD_BASE + 0xb2)
#define REG_SPD_5A_L              (REG_SPD_BASE + 0xb4)
#define REG_SPD_5B_L              (REG_SPD_BASE + 0xb6)
#define REG_SPD_5C_L              (REG_SPD_BASE + 0xb8)
#define REG_SPD_5D_L              (REG_SPD_BASE + 0xba)
#define REG_SPD_5E_L              (REG_SPD_BASE + 0xbc)
#define REG_SPD_5F_L              (REG_SPD_BASE + 0xbe)
#define REG_SPD_60_L              (REG_SPD_BASE + 0xc0)
#define REG_SPD_61_L              (REG_SPD_BASE + 0xc2)
#define REG_SPD_62_L              (REG_SPD_BASE + 0xc4)
#define REG_SPD_63_L              (REG_SPD_BASE + 0xc6)
#define REG_SPD_64_L              (REG_SPD_BASE + 0xc8)
#define REG_SPD_65_L              (REG_SPD_BASE + 0xca)
#define REG_SPD_66_L              (REG_SPD_BASE + 0xcc)
#define REG_SPD_67_L              (REG_SPD_BASE + 0xce)
#define REG_SPD_68_L              (REG_SPD_BASE + 0xd0)
#define REG_SPD_69_L              (REG_SPD_BASE + 0xd2)
#define REG_SPD_6A_L              (REG_SPD_BASE + 0xd4)
#define REG_SPD_6B_L              (REG_SPD_BASE + 0xd6)
#define REG_SPD_6C_L              (REG_SPD_BASE + 0xd8)
#define REG_SPD_6D_L              (REG_SPD_BASE + 0xda)
#define REG_SPD_6E_L              (REG_SPD_BASE + 0xdc)
#define REG_SPD_6F_L              (REG_SPD_BASE + 0xde)
#define REG_SPD_70_L              (REG_SPD_BASE + 0xe0)
#define REG_SPD_71_L              (REG_SPD_BASE + 0xe2)
#define REG_SPD_72_L              (REG_SPD_BASE + 0xe4)
#define REG_SPD_73_L              (REG_SPD_BASE + 0xe6)
#define REG_SPD_74_L              (REG_SPD_BASE + 0xe8)
#define REG_SPD_75_L              (REG_SPD_BASE + 0xea)
#define REG_SPD_76_L              (REG_SPD_BASE + 0xec)
#define REG_SPD_77_L              (REG_SPD_BASE + 0xee)
#define REG_SPD_78_L              (REG_SPD_BASE + 0xf0)
#define REG_SPD_79_L              (REG_SPD_BASE + 0xf2)
#define REG_SPD_7A_L              (REG_SPD_BASE + 0xf4)
#define REG_SPD_7B_L              (REG_SPD_BASE + 0xf6)
#define REG_SPD_7C_L              (REG_SPD_BASE + 0xf8)
#define REG_SPD_7D_L              (REG_SPD_BASE + 0xfa)
#define REG_SPD_7E_L              (REG_SPD_BASE + 0xfc)
#define REG_SPD_7F_L              (REG_SPD_BASE + 0xfe)
// h0000, bit: 7
/* infoframe type =0x81*/
#define offset_of_vs_hd_infoframe_type_code (0x0)
#define mask_of_vs_hd_infoframe_type_code   (0xff)
#define shift_of_vs_hd_infoframe_type_code  (0)
#define VS_HD_INFOFRAME_TYPE_CODE           (REG_VS_HD_BASE + offset_of_vs_hd_infoframe_type_code)
#define REG_VS_HD_00_L                      (VS_HD_INFOFRAME_TYPE_CODE)
// h0000, bit: 15
/* version = 0x1*/
#define offset_of_vs_hd_infoframe_version_number (0x0)
#define mask_of_vs_hd_infoframe_version_number   (0xff00)
#define shift_of_vs_hd_infoframe_version_number  (8)
#define VS_HD_INFOFRAME_VERSION_NUMBER           (REG_VS_HD_BASE + offset_of_vs_hd_infoframe_version_number)
// h0001, bit: 7
/* length = 27*/
#define offset_of_vs_hd_length_of_VS (0x2)
#define mask_of_vs_hd_length_of_VS   (0xff)
#define shift_of_vs_hd_length_of_VS  (0)
#define VS_HD_LENGTH_OF_VS           (REG_VS_HD_BASE + offset_of_vs_hd_length_of_VS)
#define REG_VS_HD_01_L               (VS_HD_LENGTH_OF_VS)
#define REG_VS_HD_02_L               (REG_VS_HD_BASE + 0x4)
#define REG_VS_HD_03_L               (REG_VS_HD_BASE + 0x6)
#define REG_VS_HD_04_L               (REG_VS_HD_BASE + 0x8)
#define REG_VS_HD_05_L               (REG_VS_HD_BASE + 0xa)
#define REG_VS_HD_06_L               (REG_VS_HD_BASE + 0xc)
#define REG_VS_HD_07_L               (REG_VS_HD_BASE + 0xe)
#define REG_VS_HD_08_L               (REG_VS_HD_BASE + 0x10)
#define REG_VS_HD_09_L               (REG_VS_HD_BASE + 0x12)
#define REG_VS_HD_0A_L               (REG_VS_HD_BASE + 0x14)
#define REG_VS_HD_0B_L               (REG_VS_HD_BASE + 0x16)
#define REG_VS_HD_0C_L               (REG_VS_HD_BASE + 0x18)
#define REG_VS_HD_0D_L               (REG_VS_HD_BASE + 0x1a)
#define REG_VS_HD_0E_L               (REG_VS_HD_BASE + 0x1c)
#define REG_VS_HD_0F_L               (REG_VS_HD_BASE + 0x1e)
#define REG_VS_HD_10_L               (REG_VS_HD_BASE + 0x20)
#define REG_VS_HD_11_L               (REG_VS_HD_BASE + 0x22)
#define REG_VS_HD_12_L               (REG_VS_HD_BASE + 0x24)
#define REG_VS_HD_13_L               (REG_VS_HD_BASE + 0x26)
#define REG_VS_HD_14_L               (REG_VS_HD_BASE + 0x28)
#define REG_VS_HD_15_L               (REG_VS_HD_BASE + 0x2a)
#define REG_VS_HD_16_L               (REG_VS_HD_BASE + 0x2c)
#define REG_VS_HD_17_L               (REG_VS_HD_BASE + 0x2e)
#define REG_VS_HD_18_L               (REG_VS_HD_BASE + 0x30)
#define REG_VS_HD_19_L               (REG_VS_HD_BASE + 0x32)
#define REG_VS_HD_1A_L               (REG_VS_HD_BASE + 0x34)
#define REG_VS_HD_1B_L               (REG_VS_HD_BASE + 0x36)
#define REG_VS_HD_1C_L               (REG_VS_HD_BASE + 0x38)
#define REG_VS_HD_1D_L               (REG_VS_HD_BASE + 0x3a)
#define REG_VS_HD_1E_L               (REG_VS_HD_BASE + 0x3c)
#define REG_VS_HD_1F_L               (REG_VS_HD_BASE + 0x3e)
#define REG_VS_HD_20_L               (REG_VS_HD_BASE + 0x40)
#define REG_VS_HD_21_L               (REG_VS_HD_BASE + 0x42)
#define REG_VS_HD_22_L               (REG_VS_HD_BASE + 0x44)
#define REG_VS_HD_23_L               (REG_VS_HD_BASE + 0x46)
#define REG_VS_HD_24_L               (REG_VS_HD_BASE + 0x48)
#define REG_VS_HD_25_L               (REG_VS_HD_BASE + 0x4a)
#define REG_VS_HD_26_L               (REG_VS_HD_BASE + 0x4c)
#define REG_VS_HD_27_L               (REG_VS_HD_BASE + 0x4e)
#define REG_VS_HD_28_L               (REG_VS_HD_BASE + 0x50)
#define REG_VS_HD_29_L               (REG_VS_HD_BASE + 0x52)
#define REG_VS_HD_2A_L               (REG_VS_HD_BASE + 0x54)
#define REG_VS_HD_2B_L               (REG_VS_HD_BASE + 0x56)
#define REG_VS_HD_2C_L               (REG_VS_HD_BASE + 0x58)
#define REG_VS_HD_2D_L               (REG_VS_HD_BASE + 0x5a)
#define REG_VS_HD_2E_L               (REG_VS_HD_BASE + 0x5c)
#define REG_VS_HD_2F_L               (REG_VS_HD_BASE + 0x5e)
#define REG_VS_HD_30_L               (REG_VS_HD_BASE + 0x60)
#define REG_VS_HD_31_L               (REG_VS_HD_BASE + 0x62)
#define REG_VS_HD_32_L               (REG_VS_HD_BASE + 0x64)
#define REG_VS_HD_33_L               (REG_VS_HD_BASE + 0x66)
#define REG_VS_HD_34_L               (REG_VS_HD_BASE + 0x68)
#define REG_VS_HD_35_L               (REG_VS_HD_BASE + 0x6a)
#define REG_VS_HD_36_L               (REG_VS_HD_BASE + 0x6c)
#define REG_VS_HD_37_L               (REG_VS_HD_BASE + 0x6e)
#define REG_VS_HD_38_L               (REG_VS_HD_BASE + 0x70)
#define REG_VS_HD_39_L               (REG_VS_HD_BASE + 0x72)
#define REG_VS_HD_3A_L               (REG_VS_HD_BASE + 0x74)
#define REG_VS_HD_3B_L               (REG_VS_HD_BASE + 0x76)
#define REG_VS_HD_3C_L               (REG_VS_HD_BASE + 0x78)
#define REG_VS_HD_3D_L               (REG_VS_HD_BASE + 0x7a)
#define REG_VS_HD_3E_L               (REG_VS_HD_BASE + 0x7c)
#define REG_VS_HD_3F_L               (REG_VS_HD_BASE + 0x7e)
#define REG_VS_HD_40_L               (REG_VS_HD_BASE + 0x80)
#define REG_VS_HD_41_L               (REG_VS_HD_BASE + 0x82)
#define REG_VS_HD_42_L               (REG_VS_HD_BASE + 0x84)
#define REG_VS_HD_43_L               (REG_VS_HD_BASE + 0x86)
#define REG_VS_HD_44_L               (REG_VS_HD_BASE + 0x88)
#define REG_VS_HD_45_L               (REG_VS_HD_BASE + 0x8a)
#define REG_VS_HD_46_L               (REG_VS_HD_BASE + 0x8c)
#define REG_VS_HD_47_L               (REG_VS_HD_BASE + 0x8e)
#define REG_VS_HD_48_L               (REG_VS_HD_BASE + 0x90)
#define REG_VS_HD_49_L               (REG_VS_HD_BASE + 0x92)
#define REG_VS_HD_4A_L               (REG_VS_HD_BASE + 0x94)
#define REG_VS_HD_4B_L               (REG_VS_HD_BASE + 0x96)
#define REG_VS_HD_4C_L               (REG_VS_HD_BASE + 0x98)
#define REG_VS_HD_4D_L               (REG_VS_HD_BASE + 0x9a)
#define REG_VS_HD_4E_L               (REG_VS_HD_BASE + 0x9c)
#define REG_VS_HD_4F_L               (REG_VS_HD_BASE + 0x9e)
#define REG_VS_HD_50_L               (REG_VS_HD_BASE + 0xa0)
#define REG_VS_HD_51_L               (REG_VS_HD_BASE + 0xa2)
#define REG_VS_HD_52_L               (REG_VS_HD_BASE + 0xa4)
#define REG_VS_HD_53_L               (REG_VS_HD_BASE + 0xa6)
#define REG_VS_HD_54_L               (REG_VS_HD_BASE + 0xa8)
#define REG_VS_HD_55_L               (REG_VS_HD_BASE + 0xaa)
#define REG_VS_HD_56_L               (REG_VS_HD_BASE + 0xac)
#define REG_VS_HD_57_L               (REG_VS_HD_BASE + 0xae)
#define REG_VS_HD_58_L               (REG_VS_HD_BASE + 0xb0)
#define REG_VS_HD_59_L               (REG_VS_HD_BASE + 0xb2)
#define REG_VS_HD_5A_L               (REG_VS_HD_BASE + 0xb4)
#define REG_VS_HD_5B_L               (REG_VS_HD_BASE + 0xb6)
#define REG_VS_HD_5C_L               (REG_VS_HD_BASE + 0xb8)
#define REG_VS_HD_5D_L               (REG_VS_HD_BASE + 0xba)
#define REG_VS_HD_5E_L               (REG_VS_HD_BASE + 0xbc)
#define REG_VS_HD_5F_L               (REG_VS_HD_BASE + 0xbe)
#define REG_VS_HD_60_L               (REG_VS_HD_BASE + 0xc0)
#define REG_VS_HD_61_L               (REG_VS_HD_BASE + 0xc2)
#define REG_VS_HD_62_L               (REG_VS_HD_BASE + 0xc4)
#define REG_VS_HD_63_L               (REG_VS_HD_BASE + 0xc6)
#define REG_VS_HD_64_L               (REG_VS_HD_BASE + 0xc8)
#define REG_VS_HD_65_L               (REG_VS_HD_BASE + 0xca)
#define REG_VS_HD_66_L               (REG_VS_HD_BASE + 0xcc)
#define REG_VS_HD_67_L               (REG_VS_HD_BASE + 0xce)
#define REG_VS_HD_68_L               (REG_VS_HD_BASE + 0xd0)
#define REG_VS_HD_69_L               (REG_VS_HD_BASE + 0xd2)
#define REG_VS_HD_6A_L               (REG_VS_HD_BASE + 0xd4)
#define REG_VS_HD_6B_L               (REG_VS_HD_BASE + 0xd6)
#define REG_VS_HD_6C_L               (REG_VS_HD_BASE + 0xd8)
#define REG_VS_HD_6D_L               (REG_VS_HD_BASE + 0xda)
#define REG_VS_HD_6E_L               (REG_VS_HD_BASE + 0xdc)
#define REG_VS_HD_6F_L               (REG_VS_HD_BASE + 0xde)
#define REG_VS_HD_70_L               (REG_VS_HD_BASE + 0xe0)
#define REG_VS_HD_71_L               (REG_VS_HD_BASE + 0xe2)
#define REG_VS_HD_72_L               (REG_VS_HD_BASE + 0xe4)
#define REG_VS_HD_73_L               (REG_VS_HD_BASE + 0xe6)
#define REG_VS_HD_74_L               (REG_VS_HD_BASE + 0xe8)
#define REG_VS_HD_75_L               (REG_VS_HD_BASE + 0xea)
#define REG_VS_HD_76_L               (REG_VS_HD_BASE + 0xec)
#define REG_VS_HD_77_L               (REG_VS_HD_BASE + 0xee)
#define REG_VS_HD_78_L               (REG_VS_HD_BASE + 0xf0)
#define REG_VS_HD_79_L               (REG_VS_HD_BASE + 0xf2)
#define REG_VS_HD_7A_L               (REG_VS_HD_BASE + 0xf4)
#define REG_VS_HD_7B_L               (REG_VS_HD_BASE + 0xf6)
#define REG_VS_HD_7C_L               (REG_VS_HD_BASE + 0xf8)
#define REG_VS_HD_7D_L               (REG_VS_HD_BASE + 0xfa)
#define REG_VS_HD_7E_L               (REG_VS_HD_BASE + 0xfc)
#define REG_VS_HD_7F_L               (REG_VS_HD_BASE + 0xfe)
// h0000, bit: 7
/* checksum*/
#define offset_of_vs_checksum (0x0)
#define mask_of_vs_checksum   (0xff)
#define shift_of_vs_checksum  (0)
#define VS_CHECKSUM           (REG_VS_BASE + offset_of_vs_checksum)
#define REG_VS_00_L           (VS_CHECKSUM)
// h0000, bit: 15
/* 24bit IEEE reg ID = 0x000C03*/
#define offset_of_vs_IEEE_reg_id_0 (0x0)
#define mask_of_vs_IEEE_reg_id_0   (0xff00)
#define shift_of_vs_IEEE_reg_id_0  (8)
#define VS_IEEE_REG_ID_0           (REG_VS_BASE + offset_of_vs_IEEE_reg_id_0)
// h0001, bit: 15
/* 24bit IEEE reg ID = 0x000C03*/
#define offset_of_vs_IEEE_reg_id_1 (0x2)
#define mask_of_vs_IEEE_reg_id_1   (0xffff)
#define shift_of_vs_IEEE_reg_id_1  (0)
#define VS_IEEE_REG_ID_1           (REG_VS_BASE + offset_of_vs_IEEE_reg_id_1)
#define REG_VS_01_L                (VS_IEEE_REG_ID_1)
// h0002, bit: 7
/* video forma:
000:no additional HDMI video format is present in this packet
001:extend resolution format present (eg. Used for 4k2k)
010:3D format
else: reserve*/
#define offset_of_vs_HDMI_video_format (0x4)
#define mask_of_vs_HDMI_video_format   (0xe0)
#define shift_of_vs_HDMI_video_format  (5)
#define VS_HDMI_VIDEO_FORMAT           (REG_VS_BASE + offset_of_vs_HDMI_video_format)
#define REG_VS_02_L                    (VS_HDMI_VIDEO_FORMAT)
// h0003, bit: 3
/* if is HDMI_VIC is 1byte, if is 3d structure is 4 bit at 4-7bit*/
#define offset_of_vs_HDMI_VIC (0x6)
#define mask_of_vs_HDMI_VIC   (0xf)
#define shift_of_vs_HDMI_VIC  (0)
#define VS_HDMI_VIC           (REG_VS_BASE + offset_of_vs_HDMI_VIC)
#define REG_VS_03_L           (VS_HDMI_VIC)
// h0003, bit: 7
/* 3d_ext_data*/
#define offset_of_vs_3d_ext_data (0x6)
#define mask_of_vs_3d_ext_data   (0xf0)
#define shift_of_vs_3d_ext_data  (4)
#define VS_3D_EXT_DATA           (REG_VS_BASE + offset_of_vs_3d_ext_data)
#define REG_VS_04_L              (REG_VS_BASE + 0x8)
#define REG_VS_05_L              (REG_VS_BASE + 0xa)
#define REG_VS_06_L              (REG_VS_BASE + 0xc)
#define REG_VS_07_L              (REG_VS_BASE + 0xe)
#define REG_VS_08_L              (REG_VS_BASE + 0x10)
#define REG_VS_09_L              (REG_VS_BASE + 0x12)
#define REG_VS_0A_L              (REG_VS_BASE + 0x14)
#define REG_VS_0B_L              (REG_VS_BASE + 0x16)
#define REG_VS_0C_L              (REG_VS_BASE + 0x18)
#define REG_VS_0D_L              (REG_VS_BASE + 0x1a)
#define REG_VS_0E_L              (REG_VS_BASE + 0x1c)
#define REG_VS_0F_L              (REG_VS_BASE + 0x1e)
#define REG_VS_10_L              (REG_VS_BASE + 0x20)
#define REG_VS_11_L              (REG_VS_BASE + 0x22)
#define REG_VS_12_L              (REG_VS_BASE + 0x24)
#define REG_VS_13_L              (REG_VS_BASE + 0x26)
#define REG_VS_14_L              (REG_VS_BASE + 0x28)
#define REG_VS_15_L              (REG_VS_BASE + 0x2a)
#define REG_VS_16_L              (REG_VS_BASE + 0x2c)
#define REG_VS_17_L              (REG_VS_BASE + 0x2e)
#define REG_VS_18_L              (REG_VS_BASE + 0x30)
#define REG_VS_19_L              (REG_VS_BASE + 0x32)
#define REG_VS_1A_L              (REG_VS_BASE + 0x34)
#define REG_VS_1B_L              (REG_VS_BASE + 0x36)
#define REG_VS_1C_L              (REG_VS_BASE + 0x38)
#define REG_VS_1D_L              (REG_VS_BASE + 0x3a)
#define REG_VS_1E_L              (REG_VS_BASE + 0x3c)
#define REG_VS_1F_L              (REG_VS_BASE + 0x3e)
#define REG_VS_20_L              (REG_VS_BASE + 0x40)
#define REG_VS_21_L              (REG_VS_BASE + 0x42)
#define REG_VS_22_L              (REG_VS_BASE + 0x44)
#define REG_VS_23_L              (REG_VS_BASE + 0x46)
#define REG_VS_24_L              (REG_VS_BASE + 0x48)
#define REG_VS_25_L              (REG_VS_BASE + 0x4a)
#define REG_VS_26_L              (REG_VS_BASE + 0x4c)
#define REG_VS_27_L              (REG_VS_BASE + 0x4e)
#define REG_VS_28_L              (REG_VS_BASE + 0x50)
#define REG_VS_29_L              (REG_VS_BASE + 0x52)
#define REG_VS_2A_L              (REG_VS_BASE + 0x54)
#define REG_VS_2B_L              (REG_VS_BASE + 0x56)
#define REG_VS_2C_L              (REG_VS_BASE + 0x58)
#define REG_VS_2D_L              (REG_VS_BASE + 0x5a)
#define REG_VS_2E_L              (REG_VS_BASE + 0x5c)
#define REG_VS_2F_L              (REG_VS_BASE + 0x5e)
#define REG_VS_30_L              (REG_VS_BASE + 0x60)
#define REG_VS_31_L              (REG_VS_BASE + 0x62)
#define REG_VS_32_L              (REG_VS_BASE + 0x64)
#define REG_VS_33_L              (REG_VS_BASE + 0x66)
#define REG_VS_34_L              (REG_VS_BASE + 0x68)
#define REG_VS_35_L              (REG_VS_BASE + 0x6a)
#define REG_VS_36_L              (REG_VS_BASE + 0x6c)
#define REG_VS_37_L              (REG_VS_BASE + 0x6e)
#define REG_VS_38_L              (REG_VS_BASE + 0x70)
#define REG_VS_39_L              (REG_VS_BASE + 0x72)
#define REG_VS_3A_L              (REG_VS_BASE + 0x74)
#define REG_VS_3B_L              (REG_VS_BASE + 0x76)
#define REG_VS_3C_L              (REG_VS_BASE + 0x78)
#define REG_VS_3D_L              (REG_VS_BASE + 0x7a)
#define REG_VS_3E_L              (REG_VS_BASE + 0x7c)
#define REG_VS_3F_L              (REG_VS_BASE + 0x7e)
#define REG_VS_40_L              (REG_VS_BASE + 0x80)
#define REG_VS_41_L              (REG_VS_BASE + 0x82)
#define REG_VS_42_L              (REG_VS_BASE + 0x84)
#define REG_VS_43_L              (REG_VS_BASE + 0x86)
#define REG_VS_44_L              (REG_VS_BASE + 0x88)
#define REG_VS_45_L              (REG_VS_BASE + 0x8a)
#define REG_VS_46_L              (REG_VS_BASE + 0x8c)
#define REG_VS_47_L              (REG_VS_BASE + 0x8e)
#define REG_VS_48_L              (REG_VS_BASE + 0x90)
#define REG_VS_49_L              (REG_VS_BASE + 0x92)
#define REG_VS_4A_L              (REG_VS_BASE + 0x94)
#define REG_VS_4B_L              (REG_VS_BASE + 0x96)
#define REG_VS_4C_L              (REG_VS_BASE + 0x98)
#define REG_VS_4D_L              (REG_VS_BASE + 0x9a)
#define REG_VS_4E_L              (REG_VS_BASE + 0x9c)
#define REG_VS_4F_L              (REG_VS_BASE + 0x9e)
#define REG_VS_50_L              (REG_VS_BASE + 0xa0)
#define REG_VS_51_L              (REG_VS_BASE + 0xa2)
#define REG_VS_52_L              (REG_VS_BASE + 0xa4)
#define REG_VS_53_L              (REG_VS_BASE + 0xa6)
#define REG_VS_54_L              (REG_VS_BASE + 0xa8)
#define REG_VS_55_L              (REG_VS_BASE + 0xaa)
#define REG_VS_56_L              (REG_VS_BASE + 0xac)
#define REG_VS_57_L              (REG_VS_BASE + 0xae)
#define REG_VS_58_L              (REG_VS_BASE + 0xb0)
#define REG_VS_59_L              (REG_VS_BASE + 0xb2)
#define REG_VS_5A_L              (REG_VS_BASE + 0xb4)
#define REG_VS_5B_L              (REG_VS_BASE + 0xb6)
#define REG_VS_5C_L              (REG_VS_BASE + 0xb8)
#define REG_VS_5D_L              (REG_VS_BASE + 0xba)
#define REG_VS_5E_L              (REG_VS_BASE + 0xbc)
#define REG_VS_5F_L              (REG_VS_BASE + 0xbe)
#define REG_VS_60_L              (REG_VS_BASE + 0xc0)
#define REG_VS_61_L              (REG_VS_BASE + 0xc2)
#define REG_VS_62_L              (REG_VS_BASE + 0xc4)
#define REG_VS_63_L              (REG_VS_BASE + 0xc6)
#define REG_VS_64_L              (REG_VS_BASE + 0xc8)
#define REG_VS_65_L              (REG_VS_BASE + 0xca)
#define REG_VS_66_L              (REG_VS_BASE + 0xcc)
#define REG_VS_67_L              (REG_VS_BASE + 0xce)
#define REG_VS_68_L              (REG_VS_BASE + 0xd0)
#define REG_VS_69_L              (REG_VS_BASE + 0xd2)
#define REG_VS_6A_L              (REG_VS_BASE + 0xd4)
#define REG_VS_6B_L              (REG_VS_BASE + 0xd6)
#define REG_VS_6C_L              (REG_VS_BASE + 0xd8)
#define REG_VS_6D_L              (REG_VS_BASE + 0xda)
#define REG_VS_6E_L              (REG_VS_BASE + 0xdc)
#define REG_VS_6F_L              (REG_VS_BASE + 0xde)
#define REG_VS_70_L              (REG_VS_BASE + 0xe0)
#define REG_VS_71_L              (REG_VS_BASE + 0xe2)
#define REG_VS_72_L              (REG_VS_BASE + 0xe4)
#define REG_VS_73_L              (REG_VS_BASE + 0xe6)
#define REG_VS_74_L              (REG_VS_BASE + 0xe8)
#define REG_VS_75_L              (REG_VS_BASE + 0xea)
#define REG_VS_76_L              (REG_VS_BASE + 0xec)
#define REG_VS_77_L              (REG_VS_BASE + 0xee)
#define REG_VS_78_L              (REG_VS_BASE + 0xf0)
#define REG_VS_79_L              (REG_VS_BASE + 0xf2)
#define REG_VS_7A_L              (REG_VS_BASE + 0xf4)
#define REG_VS_7B_L              (REG_VS_BASE + 0xf6)
#define REG_VS_7C_L              (REG_VS_BASE + 0xf8)
#define REG_VS_7D_L              (REG_VS_BASE + 0xfa)
#define REG_VS_7E_L              (REG_VS_BASE + 0xfc)
#define REG_VS_7F_L              (REG_VS_BASE + 0xfe)
#endif
