ifeq ($(CONFIG_INFINITY5),y)
obj-y += snr_cfg_infinity5.o
else ifeq ($(CONFIG_INFINITY6),y)
obj-y += snr_cfg_infinity6.o
else ifeq ($(CONFIG_INFINITY6E),y)
obj-y += snr_cfg_infinity6e.o
else ifeq ($(CONFIG_INFINITY6B0),y)
obj-y += snr_cfg_infinity6b0.o
else
obj-y += clk_pad.o
endif
